development:
  adapter: mysql2
  encoding: utf8
  database: db/blog_development
  pool: 5
  username: root
  password: LilyLindo8678!
test:
  adapter: mysql2
  encoding: utf8
  database: db/blog_test
  pool: 5
  username: root
  password: LilyLindo8678!
production:
  adapter: mysql2
  encoding: utf8
  database: db/blog_production
  url: <%= ENV['DATABASE_URL'] %>
  pool: 5
  username: root
  password: LilyLindo8678!
